apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kubernetes-django
  template:
    metadata:
      labels:
        run: kubernetes-django
    spec:
      containers:
      - name: kubernetes-django
        image: kubernetes-django
        ports:
        - containerPort: 8000
#        
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-django
spec:
  selector:
    run: kubernetes-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 
